# todo : https://android.googlesource.com/platform/build/+/master/tools/docker/Dockerfile

# android-build-image with Ubuntu
# https://nathanpfry.com/how-to-setup-ubuntu-18-04-lts-bionic-beaver-to-compile-android-roms/
# https://source.android.com/docs/setup/start/initializing
# https://source.android.com/docs/setup/start/older-versions

FROM docker.io/library/ubuntu:10.04

LABEL maintainer = Julien Milletre Akipe <code.julien@milletre.fr>

ENV \
    # user
    UID=1000 \
    GID=1000 \
    # ccache specifics
    CCACHE_SIZE=50G \
    CCACHE_DIR=/android/ccache \
    USE_CCACHE=1 \
    CCACHE_COMPRESS=1 \
    # java
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk \
    ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G" \
    # other
    LC_ALL=C

######
### Init Archlinux
######

RUN rm /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-security main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-proposed main restricted universe multiverse" >> /etc/apt/sources.list \
    && cat /etc/apt/sources.list

RUN echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/70-allow-unauthenticated

# Upgrade Archlinux and install devel packages
RUN apt-get update \
    && echo "udev hold" | dpkg --set-selections \
    && echo "plymouth hold" | dpkg --set-selections \
    && apt-get dist-upgrade --yes \
    && apt-get install --yes \
        git-core \
        gnupg \
        flex \
        bison \
        gperf \
        build-essential \
        zip \
        curl \
        zlib1g-dev \
        libc6-dev \
        lib32ncurses5-dev \
        ia32-libs \
        x11proto-core-dev \
        libx11-dev \
        lib32readline5-dev \
        lib32z-dev \
        libgl1-mesa-dev \
        mingw32 \
        tofrodos \
        python-markdown \
        libxml2-utils \
        xsltproc \
        python-pip \
        python-virtualenv \
        python-software-properties \
        sudo \
    # && apt-get install --yes --no-install-recommends openjdk-7-jdk
    && add-apt-repository ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install --no-install-recommends openjdk-7-jdk openjdk-6-jdk -f --yes \
    && ln -s /usr/lib32/mesa/libGL.so.1 /usr/lib32/mesa/libGL.so

RUN curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo \
    && chmod a+x /usr/bin/repo

# RUN pip install virtualenv

######
### Create user
######

RUN groupadd --gid $GID --force builder \
    && useradd --gid $GID --uid $UID --non-unique builder \
    && mkdir /home/builder \
    && chown -R builder:builder /home/builder \
    && echo "builder ALL=NOPASSWD: ALL" > /etc/sudoers.d/builder

######
### Android build tools
######

# Create working directory
RUN mkdir /android \
    && chown -R builder:builder /android

WORKDIR /android

# Configure Python version
# RUN virtualenv --system-site-packages venv
#    && ln -s /usr/lib/python2.7/* /android/venv/lib/python2.7/ \
#    && source venv/bin/activate

COPY ./entrypoint.sh /

RUN chmod +x /entrypoint.sh \
    && chown -R builder:builder /entrypoint.sh

USER builder

CMD /entrypoint.sh
