# Android 5.0

FROM ak1pe/android-aosp-build:ubuntu-12.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

USER root

# Install openjdk 7
RUN apt-get update \
    && apt-get dist-upgrade --yes \
    && apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && apt-get install --yes --no-install-recommends \
        openjdk-7-jdk

RUN update-alternatives --set java "/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java" && \
    update-alternatives --set javac "/usr/lib/jvm/java-7-openjdk-amd64/bin/javac"

USER builder

CMD /entrypoint.sh
