# Android 2.3.x to Android 4.4.x

# FROM localhost/android-aosp-build-base:ubuntu-12.04
FROM ak1pe/android-aosp-build-base:ubuntu-12.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/jdk1.6.0_45

USER root

COPY ./assets/jdk-6u45-linux-x64.bin /tmp

# Install java jdk 6
RUN echo "6b493aeab16c940cae9e3d07ad2a5c5684fb49cf06c5d44c400c7993db0d12e8  /tmp/jdk-6u45-linux-x64.bin" | sha256sum --strict --check - \
    && apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && export JAVA_INSTALL_DIR=$(mktemp --directory) \
    && mv /tmp/jdk-6u45-linux-x64.bin $JAVA_INSTALL_DIR \
    && cd $JAVA_INSTALL_DIR \
    && chmod +x $JAVA_INSTALL_DIR/jdk-6u45-linux-x64.bin \
    && $JAVA_INSTALL_DIR/jdk-6u45-linux-x64.bin \
    && mkdir -p /usr/lib/jvm \
    && mv $JAVA_INSTALL_DIR/jdk1.6.0_45 /usr/lib/jvm/ \
    && update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.6.0_45/bin/java" 1 \
    && update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.6.0_45/bin/javac" 1 \
    && update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.6.0_45/bin/javaws" 1 \
    && export PATH=$PATH:$JAVA_HOME/bin \
    && rm -rf "$JAVA_INSTALL_DIR"

USER $USERNAME

ENTRYPOINT ["/entrypoint.sh"]
