# Android 7.0 to Android 8.0

# FROM localhost/android-aosp-build-base:ubuntu-14.04
FROM ak1pe/android-aosp-build-base:ubuntu-14.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

USER root

# Install openjdk 8
RUN export JAVA_INSTALL_DIR=$(mktemp --directory) \
    && curl -o $JAVA_INSTALL_DIR/jdk8.tgz https://android.googlesource.com/platform/prebuilts/jdk/jdk8/+archive/master.tar.gz \
    && cd $JAVA_INSTALL_DIR \
    && tar -zxf $JAVA_INSTALL_DIR/jdk8.tgz linux-x86 \
    && mv $JAVA_INSTALL_DIR/linux-x86 /usr/lib/jvm/java-8-openjdk-amd64 \
    && rm -rf $JAVA_INSTALL_DIR

ENV PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH

USER $USERNAME

ENTRYPOINT ["/entrypoint.sh"]
