# Android 7.0 to Android 8.0

FROM ak1pe/android-aosp-build:ubuntu-14.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

USER root

# Install openjdk 8
RUN wget -O /tmp/openjdk-8-jre-headless_8u45-b14-1_amd64.deb http://old-releases.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre-headless_8u45-b14-1_amd64.deb && \
    wget -O /tmp/openjdk-8-jre_8u45-b14-1_amd64.deb http://old-releases.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jre_8u45-b14-1_amd64.deb && \
    wget -O /tmp/openjdk-8-jdk_8u45-b14-1_amd64.deb http://old-releases.ubuntu.com/ubuntu/pool/universe/o/openjdk-8/openjdk-8-jdk_8u45-b14-1_amd64.deb && \
    cd /tmp && \
    dpkg -i \
        openjdk-8-jre-headless_8u45-b14-1_amd64.deb \
        openjdk-8-jre_8u45-b14-1_amd64.deb \
        openjdk-8-jdk_8u45-b14-1_amd64.deb || true && \
    apt-get update && \
    apt-get -f --yes install

RUN update-alternatives --set java "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java" && \
    update-alternatives --set javac "/usr/lib/jvm/java-8-openjdk-amd64/bin/javac"

USER builder

CMD /entrypoint.sh
