# Android 6.0

FROM ak1pe/android-aosp-build:ubuntu-14.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
ENV ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

USER root

# Install openjdk 7
RUN apt-get update \
    && apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && apt-get dist-upgrade --yes \
    && apt-get install --yes \
        openjdk-7-jdk

RUN update-alternatives --set java "/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java" && \
    update-alternatives --set javac "/usr/lib/jvm/java-7-openjdk-amd64/bin/javac"

USER builder

CMD /entrypoint.sh
