# Android 2.3.x to Android 4.4.x

FROM android-aosp-build:ubuntu-12.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/jdk1.6.0_45

USER root

COPY ./assets/jdk-6u45-linux-x64.bin /tmp

# Install java jdk 6
RUN apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && cd /tmp && chmod +x /tmp/jdk-6u45-linux-x64.bin && \
    /tmp/jdk-6u45-linux-x64.bin && \
    mkdir -p /usr/lib/jvm && \
    mv jdk1.6.0_45 /usr/lib/jvm/ && \
    update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.6.0_45/bin/java" 1 && \
    update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.6.0_45/bin/javac" 1 && \
    update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.6.0_45/bin/javaws" 1 && \
    export PATH=$PATH:$JAVA_HOME/bin && \
    rm /tmp/jdk-6u45-linux-x64.bin

USER builder

CMD /entrypoint.sh
