# Android 7.0 to Android 8.0

# FROM localhost/android-aosp-build-base:ubuntu-18.04
FROM ak1pe/android-aosp-build-base:ubuntu-18.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G"

USER root

# Install openjdk 8
RUN apt-get update \
    && apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && apt-get full-upgrade --yes \
    && apt-get install --yes \
        openjdk-8-jdk \
    && echo "jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, include jdk.disabled.namedCurves" | tee -a /etc/java-8-openjdk/security/java.security

ENV PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH

USER $USERNAME

ENTRYPOINT ["/entrypoint.sh"]
