# Android 7.0 to Android 8.0

# FROM localhost/android-aosp-build-base:ubuntu-18.04
FROM ak1pe/android-aosp-build-base:ubuntu-18.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

USER $USERNAME

CMD /entrypoint.sh
