FROM docker.io/library/ubuntu:10.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

ENV \
    # user
    UID=1000 \
    GID=1000 \
    # ccache specifics
    CCACHE_SIZE=50G \
    CCACHE_DIR=/android/ccache \
    USE_CCACHE=1 \
    CCACHE_COMPRESS=1 \
    # java
    JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk \
    ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G" \
    # other
    LC_ALL=C

# Change packages repositories
RUN rm /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-security main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-proposed main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/70-allow-unauthenticated

# Install and upgrades packages
RUN echo "udev hold" | dpkg --set-selections \
    && echo "plymouth hold" | dpkg --set-selections \
    && apt-get update \
    && apt-get dist-upgrade --yes \
    && apt-get install --yes \
        git-core \
        gnupg \
        flex \
        bison \
        gperf \
        build-essential \
        zip \
        curl \
        zlib1g-dev \
        libc6-dev \
        lib32ncurses5-dev \
        ia32-libs \
        x11proto-core-dev \
        libx11-dev \
        lib32readline5-dev \
        lib32z-dev \
        libgl1-mesa-dev \
        mingw32 \
        tofrodos \
        python-markdown \
        libxml2-utils \
        xsltproc \
        python-pip \
        python-virtualenv \
        ccache \
        # For users
        python-software-properties \
        sudo \
        wget \
        bash-completion \
    && add-apt-repository ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install --no-install-recommends -f --yes \
        openjdk-7-jdk \
        openjdk-6-jdk \
    && ln -s /usr/lib32/mesa/libGL.so.1 /usr/lib32/mesa/libGL.so

# Install repo
RUN curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo \
    && chmod a+x /usr/bin/repo

# Create user
RUN groupadd --gid $GID --force builder \
    && useradd --gid $GID --uid $UID --non-unique builder \
    && mkdir /home/builder \
    && chown -R builder:builder /home/builder \
    && echo "builder ALL=NOPASSWD: ALL" > /etc/sudoers.d/builder

# Create the working directory
RUN mkdir /android \
    && chown -R builder:builder /android

WORKDIR /android

# Configure Python version
# RUN virtualenv --system-site-packages venv
#    && ln -s /usr/lib/python2.7/* /android/venv/lib/python2.7/ \
#    && source venv/bin/activate

# Set the entrypoint command
COPY ./assets/entrypoint.sh /

RUN chmod +x /entrypoint.sh \
    && chown -R builder:builder /entrypoint.sh

CMD /entrypoint.sh
