FROM docker.io/library/ubuntu:12.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

# user
ARG USERNAME=builder
ENV UID=1000
ENV GID=1000

# git
ENV GIT_USERNAME 'My Username'
ENV GIT_MAIL 'myemail@todefine.com'

# ccache specifics
ENV USE_CCACHE=1
ENV CCACHE_SIZE=50G
ENV CCACHE_DIR=/ccache
ENV CCACHE_COMPRESS=1
ENV CCACHE_EXEC /usr/bin/ccache

# for Android build process
ENV LC_ALL=C

# Change packages repositories
RUN rm /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ precise main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-security main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ precise-proposed main restricted universe multiverse" >> /etc/apt/sources.list

# Install and upgrades packages
RUN apt-get update \
    && apt-get dist-upgrade --yes \
    && apt-get -f --yes install \
    && apt-get install --yes \
        cpp \
        g++ \
    && apt-get install --yes \
        dpkg-dev \
        bc \
        bison \
        build-essential \
        ccache \
        curl \
        flex \
        g++-multilib \
        gcc-multilib \
        git \
        gnupg \
        gperf \
        imagemagick \
        lib32ncurses5-dev \
        lib32readline-dev \
        lib32z-dev \
        lib32z1-dev \
        libc6-dev \
        libc6-dev-i386 \
        libgl1-mesa-dev \
        libncurses5 \
        libncurses5-dev \
        libsdl1.2-dev \
        libssl-dev \
        libwxgtk2.8-dev \
        libx11-dev \
        libxml2 \
        libxml2-utils \
        pngcrush \
        python \
        python-dev \
        python-pip \
        python-virtualenv \
        python-networkx \
        python-markdown \
        python3 \
        python3-dev \
        python3-markdown \
        lzop \
        rsync \
        schedtool \
        squashfs-tools \
        unzip \
        x11proto-core-dev \
        xsltproc \
        zip \
        zlib1g-dev \
        libx11-dev:i386 \
        libreadline6-dev:i386 \
        libgl1-mesa-glx:i386 \
        mingw32 \
        tofrodos \
        python-markdown \
        zlib1g-dev:i386 \
        # ia32-libs \
        libwxgtk2.6-dev \
        libesd0-dev \
        # For users
        software-properties-common \
        python-software-properties \
        sudo \
        wget \
        p7zip-full \
        bash-completion  \
        nano \
        vim \
        emacs \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log} \
    && ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so

# Install python 3.6
RUN export PYTHON36_INSTALL_DIR=$(mktemp --directory) \
    && cd $PYTHON36_INSTALL_DIR \
    && wget -O $PYTHON36_INSTALL_DIR/Python-3.6.15.tgz https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz \
    && tar -xvf $PYTHON36_INSTALL_DIR/Python-3.6.15.tgz --directory $PYTHON36_INSTALL_DIR \
    && $PYTHON36_INSTALL_DIR/Python-3.6.15/configure --enable-optimizations \
    && make -j $(grep -c ^processor /proc/cpuinfo) install \
    && rm -rf $PYTHON36_INSTALL_DIR \
    && update-alternatives --install /usr/bin/python python /usr/bin/python2 1 \
    && update-alternatives --install /usr/bin/python python /usr/local/bin/python3.6 2

# Install repo v1
RUN curl "https://android.googlesource.com/tools/repo/+/refs/heads/repo-1/repo?format=TEXT" | base64 -d > /usr/bin/repo && \
    chmod a+x /usr/bin/repo

# Create user
RUN groupadd --gid $GID --force $USERNAME \
    && useradd --uid $UID --gid $GID --non-unique --create-home $USERNAME \
    && echo "${USERNAME} ALL=NOPASSWD: ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 "/etc/sudoers.d/${USERNAME}"

ENV USER=$USERNAME
ENV HOME="/home/${USERNAME}"

# Create peristance bash history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R ${USERNAME}:${GID} /commandhistory \
    && echo "$SNIPPET" >> "/home/${USERNAME}/.bashrc"

# Create ccache directory
RUN mkdir $CCACHE_DIR \
    && chown -R ${USERNAME}:${GID} $CCACHE_DIR

# Create the working directory
RUN mkdir /workspace \
    && chown -R ${USERNAME}:${GID} /workspace

WORKDIR /workspace

# Set the entrypoint command
COPY ./assets/entrypoint.sh /

RUN chmod +x /entrypoint.sh \
    && chown -R ${USERNAME}:${GID} /entrypoint.sh

USER $USERNAME

# Install Oh My BASH
RUN bash \
    -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" \
    --unattended

ENTRYPOINT ["/entrypoint.sh"]
