FROM docker.io/library/ubuntu:18.04

LABEL org.opencontainers.image.title="Android AOSP build image"
LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.url=https://github.com/Akipe/android-aosp-build-docker
LABEL org.opencontainers.image.authors="Julien Milletre Akipe <code.julien@milletre.fr>"
LABEL org.opencontainers.image.licenses=MIT
# LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.image.source=https://github.com/Akipe/android-aosp-build-docker
# LABEL org.opencontainers.image.version=ubuntu-18.04-$BUILD_DATE
# LABEL org.opencontainers.image.revision=$BUILD_SOURCE_CONTROL_REVISION

ENV \
    # user
    UID=1000 \
    GID=1000 \
    # ccache specifics
    CCACHE_SIZE=50G \
    CCACHE_DIR=/android/ccache \
    USE_CCACHE=1 \
    CCACHE_COMPRESS=1 \
    # java
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk \
    ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4G" \
    # other
    LC_ALL=C

# Init Archlinux

RUN cat /etc/apt/sources.list

# Install the build packages
RUN apt-get update \
    && apt-get full-upgrade --yes \
    && apt-get remove --yes \
        openjdk-* \
        icedtea-* \
    && apt-get install --yes \
        bc \
        bison \
        build-essential \
        bzip2 \
        ccache \
        curl \
        flex \
        g++-multilib \
        gcc-multilib \
        git \
        gnupg \
        gperf \
        imagemagick \
        lib32ncurses5-dev \
        lib32readline-dev \
        lib32z1-dev \
        libbz2-dev \
        libc6-dev-i386 \
        libffi-dev \
        libghc-bzlib-dev \
        libgl1-mesa-dev \
        libjpeg8-dev \
        liblz4-tool \
        libncurses5 \
        libncurses5-dev \
        libsdl1.2-dev \
        libssl-dev \
        libwxgtk3.0-dev \
        libx11-dev \
        libxml2 \
        libxml2-dev \
        libxml2-utils \
        libxslt1-dev \
        lzop \
        openjdk-8-jdk \
        optipng \
        pngcrush \
        python3-dev \
        python3-networkx \
        python3-pip \
        python-dev \
        python-networkx \
        python-pip \
        rsync \
        schedtool \
        squashfs-tools \
        sudo \
        unzip \
        x11proto-core-dev \
        xsltproc \
        zip \
        zlib1g-dev \
        fontconfig \
        libelf-dev \
        software-properties-common \
        wget

RUN curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo \
    && chmod a+x /usr/bin/repo

RUN pip install virtualenv

### Create user

RUN groupadd --gid $GID --force builder \
    && useradd --gid $GID --uid $UID --non-unique builder \
    && mkdir /home/builder \
    && chown -R builder:builder /home/builder \
    && echo "builder ALL=NOPASSWD: ALL" > /etc/sudoers.d/builder

# Android build tools

# Create working directory
RUN mkdir /android \
    && chown -R builder:builder /android

WORKDIR /android

# Configure Python version
RUN virtualenv --system-site-packages venv
#    && ln -s /usr/lib/python2.7/* /android/venv/lib/python2.7/ \
#    && source venv/bin/activate

COPY ./assets/entrypoint.sh /

RUN chmod +x /entrypoint.sh \
    && chown -R builder:builder /entrypoint.sh

USER builder

CMD /entrypoint.sh
