FROM docker.io/library/ubuntu:10.04

LABEL org.opencontainers.image.description="Android AOSP container for build system"
LABEL org.opencontainers.image.licenses=MIT

# user
ARG USERNAME=builder
ENV UID=1000
ENV GID=1000

# git
ENV GIT_USERNAME 'My Username'
ENV GIT_MAIL 'myemail@todefine.com'

# ccache specifics
ENV USE_CCACHE=1
ENV CCACHE_SIZE=50G
ENV CCACHE_DIR=/ccache
ENV CCACHE_COMPRESS=1
ENV CCACHE_EXEC /usr/bin/ccache

# for Android build process
ENV LC_ALL=C

# Change packages repositories
RUN rm /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-updates main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-security main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-backports main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo "deb http://old-releases.ubuntu.com/ubuntu/ lucid-proposed main restricted universe multiverse" >> /etc/apt/sources.list \
    && echo 'APT::Get::AllowUnauthenticated "true";' > /etc/apt/apt.conf.d/70-allow-unauthenticated

# Install and upgrades packages
RUN echo "udev hold" | dpkg --set-selections \
    && echo "plymouth hold" | dpkg --set-selections \
    && apt-get update \
    && apt-get dist-upgrade --yes \
    && apt-get install --yes \
        git-core \
        gnupg \
        flex \
        bison \
        gperf \
        build-essential \
        zip \
        curl \
        zlib1g-dev \
        libc6-dev \
        lib32ncurses5-dev \
        ia32-libs \
        x11proto-core-dev \
        libx11-dev \
        lib32readline5-dev \
        lib32z-dev \
        libgl1-mesa-dev \
        mingw32 \
        tofrodos \
        python \
        python-dev \
        python-pip \
        python-virtualenv \
        python-networkx \
        python-markdown \
        libxml2-utils \
        xsltproc \
        ccache \
        libwxgtk2.6-dev \
        libesd0-dev \
        # For users
        python-software-properties \
        sudo \
        wget \
        p7zip-full \
        bash-completion  \
        nano \
        vim \
        emacs \
    && apt-get clean autoclean \
    && apt-get autoremove --yes \
    && rm -rf /var/lib/{apt,dpkg,cache,log} \
    && ln -s /usr/lib32/mesa/libGL.so.1 /usr/lib32/mesa/libGL.so

# Install repo v1
RUN curl "https://android.googlesource.com/tools/repo/+/refs/heads/repo-1/repo?format=TEXT" | base64 -d > /usr/bin/repo && \
    chmod a+x /usr/bin/repo

# Create user
RUN groupadd --gid $GID --force $USERNAME \
    && useradd --uid $UID --gid $GID --non-unique --create-home $USERNAME \
    && echo "${USERNAME} ALL=NOPASSWD: ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 "/etc/sudoers.d/${USERNAME}"

ENV USER=$USERNAME
ENV HOME="/home/${USERNAME}"

# Create peristance bash history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R ${USERNAME}:${GID} /commandhistory \
    && echo "$SNIPPET" >> "/home/${USERNAME}/.bashrc"

# Create ccache directory
RUN mkdir $CCACHE_DIR \
    && chown -R ${USERNAME}:${GID} $CCACHE_DIR

# Create the working directory
RUN mkdir /workspace \
    && chown -R ${USERNAME}:${GID} /workspace

WORKDIR /workspace

# Set the entrypoint command
COPY ./assets/entrypoint.sh /

RUN chmod +x /entrypoint.sh \
    && chown -R ${USERNAME}:${GID} /entrypoint.sh

USER $USERNAME

ENTRYPOINT ["/entrypoint.sh"]
